"""Add missing FreeAgent contact columns

Revision ID: cef743eb2e45
Revises: c6dfe41e8ea1
Create Date: 2025-09-03 00:34:34.136921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cef743eb2e45'
down_revision = 'c6dfe41e8ea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('quantity_reserved', sa.Integer(), nullable=True),
    sa.Column('quantity_incoming', sa.Integer(), nullable=True),
    sa.Column('asin', sa.Text(), nullable=True),
    sa.Column('fnsku', sa.Text(), nullable=True),
    sa.Column('fulfillment_center', sa.Text(), nullable=True),
    sa.Column('inventory_id', sa.Text(), nullable=True),
    sa.Column('inventory_name', sa.Text(), nullable=True),
    sa.Column('fulfillable_quantity', sa.Integer(), nullable=True),
    sa.Column('backordered_quantity', sa.Integer(), nullable=True),
    sa.Column('exception_quantity', sa.Integer(), nullable=True),
    sa.Column('internal_transfer_quantity', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('sku', 'source')
    )
    op.create_index('ix_inventory_last_updated', 'inventory', ['last_updated'], unique=False)
    op.create_index('ix_inventory_sku_source', 'inventory', ['sku', 'source'], unique=False)
    op.create_index('ix_inventory_source', 'inventory', ['source'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('marketplace_id', sa.Text(), nullable=True),
    sa.Column('shopify_internal_id', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.Text(), nullable=True),
    sa.Column('carrier', sa.Text(), nullable=True),
    sa.Column('tracking_url', sa.Text(), nullable=True),
    sa.Column('tracking_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('ix_orders_purchase_date', 'orders', ['purchase_date'], unique=False)
    op.create_index('ix_orders_source_purchase_date', 'orders', ['source', sa.literal_column('purchase_date DESC')], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_tracking_updated', 'orders', ['tracking_updated_at'], unique=False)
    op.create_table('settlements',
    sa.Column('settlement_id', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gross', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refunds', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('settlement_id')
    )
    op.create_index('ix_settlements_period_end', 'settlements', ['period_end'], unique=False)
    op.create_index('ix_settlements_period_start', 'settlements', ['period_start'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('asin', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fee_estimate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'sku', name='uq_order_items_order_sku')
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_sku', 'order_items', ['sku'], unique=False)
    op.create_table('settlement_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('settlement_id', sa.Text(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fee_type', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.settlement_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id', 'order_id', 'type', 'posted_date', name='uq_settlement_lines_unique')
    )
    op.create_index('ix_settlement_lines_order_id', 'settlement_lines', ['order_id'], unique=False)
    op.create_index('ix_settlement_lines_posted_date', 'settlement_lines', ['posted_date'], unique=False)
    op.create_index('ix_settlement_lines_settlement_id', 'settlement_lines', ['settlement_id'], unique=False)
    op.drop_index(op.f('ix_sync_state_last_synced_at'), table_name='sync_state')
    op.drop_index(op.f('ix_sync_state_status'), table_name='sync_state')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_settlements_period_end'), table_name='amazon_settlements')
    op.drop_index(op.f('ix_settlements_period_start'), table_name='amazon_settlements')
    op.drop_table('amazon_settlements')
    op.drop_index(op.f('ix_shopify_orders_purchase_date'), table_name='shopify_orders')
    op.drop_index(op.f('ix_shopify_orders_shopify_internal_id'), table_name='shopify_orders')
    op.drop_table('shopify_orders')
    op.drop_index(op.f('ix_shopify_order_items_order_id'), table_name='shopify_order_items')
    op.drop_index(op.f('ix_shopify_order_items_sku'), table_name='shopify_order_items')
    op.drop_table('shopify_order_items')
    op.drop_index(op.f('ix_settlement_lines_order_id'), table_name='amazon_settlement_lines')
    op.drop_index(op.f('ix_settlement_lines_posted_date'), table_name='amazon_settlement_lines')
    op.drop_index(op.f('ix_settlement_lines_settlement_id'), table_name='amazon_settlement_lines')
    op.drop_table('amazon_settlement_lines')
    op.drop_index(op.f('ix_shipbob_inventory_last_updated'), table_name='shipbob_inventory')
    op.drop_index(op.f('ix_shipbob_inventory_sku'), table_name='shipbob_inventory')
    op.drop_table('shipbob_inventory')
    op.alter_column('shipbob_orders', 'currency',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('shopify_customers', 'phone')
    op.drop_column('shopify_products', 'handle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopify_products', sa.Column('handle', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('shopify_customers', sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('shipbob_orders', 'currency',
               existing_type=sa.TEXT(),
               server_default=sa.text("'USD'::text"),
               existing_nullable=True)
    op.create_table('shipbob_inventory',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity_on_hand', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_available', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_reserved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_incoming', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fulfillable_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('backordered_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exception_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('internal_transfer_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shipbob_inventory_pkey')),
    sa.UniqueConstraint('sku', name=op.f('uq_shipbob_inventory_sku'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shipbob_inventory_sku'), 'shipbob_inventory', ['sku'], unique=False)
    op.create_index(op.f('ix_shipbob_inventory_last_updated'), 'shipbob_inventory', ['last_updated'], unique=False)
    op.create_table('amazon_settlement_lines',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('settlement_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('fee_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('posted_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['settlement_id'], ['amazon_settlements.settlement_id'], name=op.f('settlement_lines_settlement_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('settlement_lines_pkey')),
    sa.UniqueConstraint('settlement_id', 'order_id', 'type', 'posted_date', name=op.f('uq_settlement_lines_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_settlement_lines_settlement_id'), 'amazon_settlement_lines', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_settlement_lines_posted_date'), 'amazon_settlement_lines', ['posted_date'], unique=False)
    op.create_index(op.f('ix_settlement_lines_order_id'), 'amazon_settlement_lines', ['order_id'], unique=False)
    op.create_table('shopify_order_items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shopify_orders.order_id'], name=op.f('shopify_order_items_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shopify_order_items_pkey')),
    sa.UniqueConstraint('order_id', 'sku', name=op.f('uq_shopify_order_items_order_sku'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shopify_order_items_sku'), 'shopify_order_items', ['sku'], unique=False)
    op.create_index(op.f('ix_shopify_order_items_order_id'), 'shopify_order_items', ['order_id'], unique=False)
    op.create_table('shopify_orders',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shopify_internal_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('carrier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracking_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracking_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('subtotal_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_tax', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_discounts', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confirmation_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referring_site', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landing_site', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at_shopify', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('fulfillment_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('storefront', sa.TEXT(), server_default=sa.text("'shopify'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('order_id', name=op.f('shopify_orders_pkey'))
    )
    op.create_index(op.f('ix_shopify_orders_shopify_internal_id'), 'shopify_orders', ['shopify_internal_id'], unique=False)
    op.create_index(op.f('ix_shopify_orders_purchase_date'), 'shopify_orders', ['purchase_date'], unique=False)
    op.create_table('amazon_settlements',
    sa.Column('settlement_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('gross', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('fees', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('refunds', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('net', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('settlement_id', name=op.f('settlements_pkey'))
    )
    op.create_index(op.f('ix_settlements_period_start'), 'amazon_settlements', ['period_start'], unique=False)
    op.create_index(op.f('ix_settlements_period_end'), 'amazon_settlements', ['period_end'], unique=False)
    op.create_table('sync_state',
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_sync_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=True),
    sa.Column('error_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sync_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('domain', name=op.f('sync_state_pkey'))
    )
    op.create_index(op.f('ix_sync_state_status'), 'sync_state', ['status'], unique=False)
    op.create_index(op.f('ix_sync_state_last_synced_at'), 'sync_state', ['last_synced_at'], unique=False)
    op.drop_index('ix_settlement_lines_settlement_id', table_name='settlement_lines')
    op.drop_index('ix_settlement_lines_posted_date', table_name='settlement_lines')
    op.drop_index('ix_settlement_lines_order_id', table_name='settlement_lines')
    op.drop_table('settlement_lines')
    op.drop_index('ix_order_items_sku', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_settlements_period_start', table_name='settlements')
    op.drop_index('ix_settlements_period_end', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('ix_orders_tracking_updated', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_source_purchase_date', table_name='orders')
    op.drop_index('ix_orders_purchase_date', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_inventory_source', table_name='inventory')
    op.drop_index('ix_inventory_sku_source', table_name='inventory')
    op.drop_index('ix_inventory_last_updated', table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###